---
apiVersion: v1
kind: Service
metadata:
  name: cloud-data-transfer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: cloud-data-transfer
